Elixir v node
lambdaclass/elixir_riak_core pull request #4
Opened 2022-06-16 18:18 UTC by fkrause98

- Working VNode implementation in Elixir

2022-06-21 14:51 UTC, Loco1982 requested changes
Minor spelling mistakes

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax.ex
> +  Retrive a key's value
```suggestion
  Retrieve a key's value
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax.ex
> +  def prefered_node_name(key) do
```suggestion
  def preferred_node_name(key) do
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax.ex
> +    {:ok, {_, name}} = prefered_node(key)
```suggestion
    {:ok, {_, name}} = preferred_node(key)
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax.ex
> +  defp prefered_node(key) do
```suggestion
  defp preferred_node(key) do
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax.ex
> +    {:ok, node} = prefered_node(key)
```suggestion
    {:ok, node} = preferred_node(key)
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax_vnode.ex
> +    Logger.debug("receieved handoff data with key-value #{key} #{val}")
```suggestion
    Logger.debug("received handoff data with key-value #{key} #{val}")
```

2022-06-21 14:51 UTC, Loco1982 commented on lib/riax_vnode.ex
> +    Logger.info("Receieved clear coverage: #{state} ")
```suggestion
    Logger.info("Received clear coverage: #{state} ")
```

2022-06-22 15:53 UTC, fkrause98 commented
> Minor spelling mistakes

Thanks for pointing it out, I've fixed them.

2022-06-22 16:10 UTC, facundoolano approved these changes

2022-06-22 16:36 UTC, merged